spring.application.name=StudentDetails-SB
server.port=8087
Spring.datasource.url=jdbc:mysql://localhost:3306/student
Spring.datasource.username=root
Spring.datasource.password=Divya@2006
Spring.jpa.hibernate.ddl-auto=update
Spring.jpa.show-sql=true
